var gasCity = "Corpus Gas City";
var grinForest = "Grineer Forest";
var grinGal = "Grineer Galleon";
var grinLab = "Grineer Sealab";
var grinSettle = "Grineer Settlement";
var grinShip = "Grineer Shipyard";
var corpPost = "Corpus Outpost";

window.poem = [[

    // "image.jpg", "image.jpg"
    // "image.jpg", "image.jpg", "image.jpg"
    // , "tileset": 

    { "A STORY ONCE LOST": ["image001.jpg", "image002.jpg", "image003.jpg"], "tileset": gasCity, "desc": ["", "", "I've never seen this room before (but that could just be due to me mostly playing void missions) so I suspected it might hide a Kuria up pretty high. I was right."] },
    { "RECOVERED BY FATE": ["image004.jpg", "image005.jpg", "image006.jpg"], "tileset": gasCity, "desc": ["", "", "Screenshot is finally here! Simply climb up the pipes and you will find the Kuria on top."] },
    { "THE TALE OF TWO SISTERS": ["image007.jpg", "image008.jpg", "image009.jpg"], "tileset": grinForest, "mission": "Mission: Any, Recommended: Excavation, Mobile Defense", "desc": ["This Kuria was previously found in a Deception mission and has been moved to a new location. It is now located in one of the biggest, if not the biggest tileset in Warframe: the jungle on earth.", "My best take on this would be searching for the waterfall and going to the second closest tree stump.", "Sadly this Kuria is not as awesome as it's predecessor. The old one was my favorite out of all 56 Kurias."] },
    { "WHO BORE THE SAME FACE": ["image010.jpg", "image011.jpg", "image012.jpg"], "tileset": grinForest, "mission": "Mission: Spy", "desc": ["This Kuria was previously found in a Deception mission and has been moved to a new location. It is now found inside of one of the spy vaults on Earth.", "Simply go up to the waterfall at the back of the room (easiest way to get there is by using the zipline).", "The Kuria is in the room behind the corridor. Make sure not to get caught or hack the vault first. Thanks to Captain♥♥♥♥♥♥for pointing this one out (his name will probably get censored :P)."] }
], [
    { "BORN ONE QUIET MORNING": ["image013.jpg", "image014.jpg"], "tileset": gasCity, "desc": ["", "Just jump upwards, you will eventually find it."] },
    { "AMIDST THE GREAT WAR": ["image015.jpg", "image016.jpg", "image017.jpg"], "tileset": gasCity, "mission": "Mission: Any, Recommended: Mobile Defense", "desc": ["", "", "This one was tricky as I expected the Kuria to be way higher up top. Apparently windows are an option, too."] },
    { "ALL ELDERS WERE GATHERED": ["image018.jpg", "image019.jpg"], "tileset": gasCity, "desc": ["", "When spawning on top of the tower, break the air-vent to jump down below and you're almost there."] },
    { "FOR THIS LIFE'S NEW DAWN": ["image020.jpg", "image021.jpg"], "tileset": grinForest, "desc": ["", "One of two Kurias I didn't find myself. I accidently spoilered myself with a video on this one. This is one of the most audacious and ridiculous Kurias I've encountered so far. It can be found at extraction. With enough boredom or skill you can manage to land down there by the way."] }
], [
    { "CONFUSED AND BEWILDERED": ["image022.jpg", "image023.jpg"], "tileset": grinGal, "desc": ["", "In the 'pillar'-room up really high."] },
    { "THEY JUDGED THEM AMISS": ["image024.jpg", "image025.jpg"], "tileset": grinGal, "desc": ["", "In the generator-room with the pillar in the middle look up to the lockers. You will be able to find a Kuria in one of the small bays."] },
    { "FOR THEY NEVER WITNESSED": ["image026.jpg", "image027.jpg"], "tileset": grinGal, "desc": ["", "When walking inside this room, walk downwards and get into the first door to your left. On your left side should be two crates stacked ontop of each other. Climb them and find your Kuria. If you have to walk upwards when entering the room, go into the last door on your right."] },
    { "TWO SELF-SAME AS THESE": ["image028.jpg", "image029.jpg", "image030.jpg"], "tileset": grinForest, "desc": ["This Kuria was previously found in a Deception mission and has been moved to a new location. The room has some stairs leading up.", "Simply go up the stairs and you can see a platform from there.", "I wonder what happened to the Grineer holding that Kuria. Anyway, thank you to Claviculus for giving me a good description."] }
], [
    { "A MIRRORED REFLECTION": ["image031.jpg", "image032.jpg", "image033.jpg"], "tileset": grinLab, "mission": "Mission: Capture", "desc": ["", "", "Simply walk to the end of the room and jump into the water. This Kuria is hard to miss. Also take note of the awesome screenshot I was able to take thanks to Warframe bugging out (hence me standing midair with my Arch-gun out). Luckily Kebabthief could finish the mission for me."] },
    { "HAD COME INTO LIFE": ["image034.jpg", "image035.jpg"], "tileset": grinLab, "desc": ["", "As soon as Kebabthief told me he found one in this room, I knew where to look. Pretty easy one here."] },
    { "BY WILL OF THEIR FATHER": ["image036.jpg", "image037.jpg", "image038.jpg", "image039.jpg"], "tileset": grinLab, "mission": "Mission: Any, Recommended: Mobile Defense", "desc": ["This is a common room and can be found within any mission.", "This one appeared inside a Mobile Defense mission. I guess it's a quite common in Mobile Defense missions, so you might be better off finding that Kuria there.", "Both rooms contain this weird apparatus with the Kuria ontop of it.", "This is the first time I've encountered the same Kuria in 2 different rooms. Grineer Sealab seems to be a weird place with a lot of strange room/object/mission-relations (hard to put that into words). To give you an example: There seem to be alternatives of certain rooms with broken pipes etc... I still need to figure this out."] },
    { "KEPT SAFE FROM THE KNIFE": ["image040.jpg", "image041.jpg", "image042.jpg"], "tileset": grinLab, "desc": ["", "", "Nothing much to say on this one. The room itself has a kind of unique mechanic. When you are standing in the middle and looking on the close walls, you may notice two 'levers'. Shoot both of these and you can get access to a somewhat secret room"] }
], [
    { "THEIR SAMENESS WAS SHUNNED": ["image043.jpg", "image044.jpg", "image045.jpg", "image046.jpg", "image047.jpg"], "tileset": grinLab, "desc": ["Rather complex Kuria here, when coming into this room, walk up the stairs until you see a yellow console.", "Hack the console before jumping down into the water.", "", "", "The door is now open revealing the Kuria. Thanks to Kebabthief for working that out, I didn't realize the console was part of it and thought it was just a similar room."] },
    { "AS SLAVE-LIKE AND SOILED": ["image048.jpg", "image049.jpg", "image050.jpg"], "tileset": grinLab, "desc": ["", "", "You can recognize this room by the fountain in the middle. Kuria is pretty easy to find."] },
    { "THEY TENDED THEIR STRAYS": ["image051.jpg", "image052.jpg", "image053.jpg"], "tileset": grinLab, "desc": ["", "", "Thank you once again to Terror for finding that Kuria. This room is easy to identify by the 4 small, yellow Grineer holograms. The Kuria is hidden inside one of the broken pipes. "] },
    { "REJECTED BY ALL": ["image054.jpg", "image055.jpg", "image056.jpg"], "tileset": grinLab, "desc": ["", "", "Can be a bit tricky to get to. Jump on the platform first and then simply walk up the corals."] }
], [
    { "AS BOTH GIRLS MATURED": ["image057.jpg", "image058.jpg", "image059.jpg"], "tileset": grinLab, "mission": "Mission: Rescue", "desc": ["", "", "This is the Grineer sealab rescue room (thank you to Archangel Arbie2 for pointing that out). The Kuria is hidden on the left side, you only need to get on one of the cables. Also this room is where you get Clem."] },
    { "THEIR BOND GREW IN DEPTH": ["image060.jpg", "image061.jpg", "image062.jpg"], "tileset": grinLab, "mission": "Mission: Sabotage", "desc": ["", "", "One of the two sabotage rooms (the other one contains the Manic Bombard)."] },
    { "THEY HAD THE SAME POISE": ["image063.jpg", "image064.jpg"], "tileset": grinLab, "desc": ["", "The room has a large shipwreck in the middle and poisonous mushrooms (pulsing gas clouds) that can easily kill you, so stay away from them. It's hard to describe where the Kuria is in that room but luckily there aren't many pillars to search for. This one was pretty mean, as I've been scanning the entire room on multiple occasions and never found it. Kebabthief then found it in a couple minutes."] },
    { "SAME SENSES, SAME STRENGTH": ["image065.jpg", "image066.jpg", "image067.jpg"], "tileset": grinLab, "mission": "Mission: Any, Recommended: The Second Dream (Quest)", "desc": ["", "", "Pretty rare archwing room, we ran across that one randomly. There's a ship cruising around with a laser. The Kuria is hidden towards the open end (to the left if you're trying to swim out) and seated on the black rock between two ... ummm... coral thingies."] }
], [
    { "THE UPRISING CAME": ["image068.jpg", "image069.jpg", "image070.jpg"], "tileset": grinSettle, "desc": ["", "", "This is a pretty common passage. When facing the generator, step in front of the control console and look to the left."] },
    { "AND SPREAD LIKE A WEED": ["image071.jpg", "image072.jpg"], "tileset": grinSettle, "mission": "Mission: Defense", "desc": ["", "This one can only be found in the defense-room. It is to the left of the pipes."] },
    { "AN ARMY OF COPY-MEN": ["image073.jpg", "image074.jpg", "image075.jpg"], "tileset": grinSettle, "desc": ["", "", "This one is a really mean Kuria as it is close to the extraction and the second (technically the first as it is higher up in the list) Kuria in a rather small room. Be careful if you're playing alone or all the other people are already at extraction, because stepping a bit too far to the side will immediately end the mission in case the objective has already been completed.\nThis is the second out of two Kurias (the first being Kuria 2-4) I got spoilered. I don't think I would ever have found that one myself."] },
    { "FEROCIOUS AND FREE": ["image076.jpg", "image077.jpg", "image078.jpg"], "tileset": grinSettle, "desc": ["", "", "Near the extraction."] }
], [
    { "AND MUCH LIKE THE SEA": ["image079.jpg", "image080.jpg", "image081.jpg"], "tileset": grinSettle, "desc": ["", "", "This one is a bit tricky to find. If you're looking down from the higher-located generator to the lower one, you can find the Kuria on a ledge to the right side of the narrow passage."] },
    { "THEY CAME JUST LIKE WAVES": ["image082.jpg", "image083.jpg", "image084.jpg"], "tileset": grinSettle, "desc": ["", "", "Searched in this room like a maniac during a nightmare mission but couldn't find a thing after 10 minutes. Terror found that Kuria in less than 20 seconds. The entrance is really hard to see when you're not up close."] },
    { "FOR YEARS THEY FOUGHT ON": ["image085.jpg", "image086.jpg", "image087.jpg"], "tileset": grinSettle, "desc": ["", "", "The second Kuria in the same room (with the energy generator thingy in the middle). Ironically, I found this one."] },
    { "FOR YEARS WE REMAINED": ["image088.jpg", "image089.jpg"], "tileset": grinSettle, "desc": ["", "I ran past this one far too often. Bullet-jump on the second (higher) rock pillar."] }
], [
    { "LIKE CHISEL TO STONE": ["image090.jpg", "image091.jpg", "image092.jpg"], "tileset": grinSettle, "desc": ["", "", "On top of one of the pillars in the 'desert' tile."] },
    { "WAR MOLDED THE TWINS": ["image093.jpg", "image094.jpg"], "tileset": grinLab, "desc": ["", "This room is a generic end-tile and can be found anywhere under water (credits to Claviculuswuluwus for the research)."] },
    { "WHO RAVAGED THE HORDES": ["image095.jpg", "image096.jpg"], "tileset": grinSettle, "desc": ["", "One of the spawn rooms for the Grineer settlement tileset. This room is guaranteed to appear if you select a defense mission. Just climb on top of the crane."] },
    { "BECAME LEGEND TO THEM": ["image097.jpg", "image098.jpg"], "tileset": grinShip, "desc": ["", "I don't know what to write here. Eat a snickers."] }
], [
    { "THEY HAD A DEEP STRENGTH": ["image099.jpg", "image100.jpg"], "tileset": grinShip, "desc": ["", "This room is quite rare. The Kuria is hidden in the ground, you can easily scan it."] },
    { "THAT CAME FROM EACH OTHER": ["image101.jpg", "image102.jpg"], "tileset": grinShip, "desc": ["", "This room is surprisingly common and the Kuria is on the pipes to the right of the lava. It will be one of the first you will encounter on Ceres."] },
    { "UNLIKE ALL THESE COPIES": ["image103.jpg", "image104.jpg", "image105.jpg"], "tileset": grinShip, "desc": ["", "", "This is self-explanatory. Thanks to Terror for finding this one. The only reason you're seeing text here is because there's some weird formatting bug with lists and I have to write something because I don't want it too look messy."] },
    { "IDENTICAL, BUT NOT BROTHERS": ["image106.jpg", "image107.jpg"], "tileset": grinShip, "desc": ["", "On top of the right fan over the door."] }
], [
    { "THE COPIES COULD SEE IT": ["image108.jpg", "image109.jpg", "image110.jpg"], "tileset": grinShip, "desc": ["", "", "Follow the corridor to your right when you come in. This dead-end is was guaranteed to spawn in this particular extraction-room (which seems to be the best place to find it in). Props to Fox the Undead for telling me in the comments, that this is a generic dead-end and can be found in other rooms aswell. This room could also previously be found in Orokin Sabotage missions."] },
    { "THEY YEARNED FOR IT TOO": ["image111.jpg", "image112.jpg", "image113.jpg"], "tileset": grinShip, "desc": ["", "", "This one..! In the same room as the next Kuria, except I completely missed this one. Terror found it and I didn't believe it until I found the Kuria myself later. Props to DE for that one.\nI think this room might only show up as a branch to a certain extraction room."] },
    { "IF THE TWINS COULD DO IT": ["image114.jpg"], "tileset": grinShip, "desc": ["Still in the same room as the previous Kuria. The second I looked up, I knew there would be a Kuria appearing on my scanner. I was absolutely right. Also, you can climb really high into this room. The Kuria is somewhere in the middle."] },
    { "PERHAPS THEY COULD TOO": ["image115.jpg", "image116.jpg"], "tileset": grinShip, "desc": ["", "I ran past the Kuria inside this room a couple of times before I almost accidently noticed it on my scanner. This one was a real surprise."] }
], [
    { "THE TWINS HAD ATTAINED": ["image117.jpg", "image118.jpg", "image119.jpg"], "tileset": grinShip, "desc": ["", "", "Props to Terror for finding that one. Simply stand below the platform and bullet-jump straight up. It's a bit tricky to get to, because not even a few feet above is an invisible ceiling and you don't have a lot of options to wall-jump up there."] },
    { "SOMETHING MORE THAN A WHOLE": ["image120.jpg", "image121.jpg", "image122.jpg"], "tileset": grinShip, "mission": "Mission: Any, Recommended: Mobile Defense", "desc": ["", "", "This is a pretty rare end-room but it's usually connected to another room over rails, so watch out for those. Go up towards the console and halfway there you will see a stairway that leads beneath. The Kuria is under the last flight of stairs. As lyravega pointed out, this room requires a room with rails in order to spawn, one of which is more common to spawn in Mobile Defense. Big thanks to him!"] },
    { "A TRUE UNDERSTANDING": ["image123.jpg", "image124.jpg"], "tileset": grinShip, "desc": ["", "This is apparently a super-rare extraction-room. Be careful when playing on solo because you might accidently end the mission before you get to scan the Kuria. There is a ledge on the left cliff that you can stand on. Move along until you can get a glimpse of the Kuria (credits go to sp!r!tst0ne and Total Takeover for figuring this out). Caution: don't get struck by a lightning!"] },
    { "OF EACH OTHER SOUL": ["image125.jpg", "image126.jpg", "image127.jpg", "image169.jpg"], "tileset": grinShip, "mission": "Mission: Any, Recommended: Capture", "desc": ["", "", "The last one! I knew there'd be two Kurias in this room and I finally found it in a mission where I had enough time to search for it. This one took me pretty long, because I never got this room when I was playing on Ceres every week or so. I knew I had to search this room again and the stars finally aligned!", "Addition from Southen: they've also made 12-4 a lot easier to scan"] }
], [
    { "THE COPIES BECAME BELIEVERS": ["image128.jpg", "image129.jpg"], "tileset": grinShip, "mission": "Mission: Any, Recommended: Capture", "desc": ["", "This Kuria was a big surprise to me, as I almost missed it. Scanned the entire room finding nothing and then suddenly hear it as I'm bullet-jumping out of the room. It can be found in the same room as the previous Kuria."] },
    { "ONE BY ONE BOWED TO THE TWINS": ["image130.jpg", "image131.jpg", "image132.jpg"], "tileset": grinShip, "desc": ["So after taking a lot of runs through Ceres in order to find new Kurias, Kebabthief told me he found a new one and tried to describe it. That was Kuria 12-2 but it made me remember this particular room with the three cranes which I only ever saw once. So after finishing a lot of missions on Ceres and almost giving up, thinking I did something wrong I FINALLY FOUND IT. This has to be (in my opinion) the rarest room I have encountered so far.", "", "I immediately got a feeling the Kuria would be ontop of the cranes and there it was, smiling at me. It's pretty easy to get up there but from my memory of that room I was already so sure I'd find it up there, it felt like fulfilling a prophecy."] },
    //{ "AND LED FORTH BY THEIR NEW MASTERS": ["image133.jpg", "image134.jpg"], "tileset": grinShip, "desc": ["This Kuria can be found in the exact same room as the Kuria above. Let me go ahead and tell you that I had to watch a video guide in order to find this one\nI started watching the video and realized I was right: There absolutely is a Kuria in this room! I stopped the video before I knew where exactly to look (I just needed that motivation-boost) and searched it by myself...\nfor 30 minutes...", "Out of all the Kurias I collected so far, all seemed fair in some way. Some were easy, others were hard, but I always felt like I achieved something. Every time my friends found a Kuria faster than me or got one that I missed it gave me motivation to try better next time.\nBUT THIS KURIA...\nIt's more than 50 meters away from the next platform so it doesn't show up on the scanner.\nIt's up so high, the engine just fails the lighting and your character model turns black.\nIt's so far away from the enemies, they just stop moving at all.\nIt's just...\nwrong.I can't explain how to get up there, took me 5 minutes. Just try your best. Good luck."] },
    { "AND LED FORTH BY THEIR NEW MASTERS": ["image166.jpg", "image167.jpg", "image168.jpg"], "tileset": grinShip, "desc": ["NeoDennis <a href='http://steamcommunity.com/sharedfiles/filedetails/?id=1214109711'>Source</a>", "NeoDennis <a href='http://steamcommunity.com/sharedfiles/filedetails/?id=1214109816'>Source</a>", "NeoDennis <a href='http://steamcommunity.com/sharedfiles/filedetails/?id=1214109927'>Source</a>"]},
    { "THEY RAVAGED THE COLONIES": ["image135.jpg", "image136.jpg", "image137.jpg"], "tileset": grinLab, "desc": ["", "", "One of the most recognizable rooms in Grineer Sealab-tileset. The Kuria is hidden pretty well and was a pain to search for. It's found high up on the pipes before walking up the slope. There's also a small hole in the wall near it.\nThis particular one is really confusing, I didn't expect it to be found in the Sealab-tileset, but on either Corpus Outpost or Grineer Settlement. It really throws me off, because it completely destroys the pattern I started to recognize... maybe it's just an exception."] }
], [
    { "NOW A POWER TO FOLLOW": ["image138.jpg", "image139.jpg", "image140.jpg"], "tileset": corpPost,"mission": "Mission: Any, Recommended: Excavation", "desc": ["", "", "I suspected a Kuria to be in this room (especially down there) but couldn't find one after searching for 10 minutes and gave up, thinking there would be none in there. Guess I was wrong because this room does indeed have a Kuria, I was just to clumsy to find it in the first go. (Thank you to egk2 for pointing that out in the comments)"] },
    { "NOT A FORCE TO BE FOUGHT": ["image141.jpg", "image142.jpg", "image143.jpg"], "tileset": corpPost, "desc": ["", "", "When going towards extraction, walk down the small hill and go to the left, where you will be able to find a cave (it can be hard to find depending on where you are standing). Go in there until you see a pile of scrap. The Kuria is behind the container and could be a bit tricky to scan."] },
    { "FROM THE ASHES OF WAR": ["image144.jpg", "image145.jpg", "image146.jpg"], "tileset": corpPost, "desc": ["", "", "In the corpus room with the see-through elevator. If you're walking towards the elevator, look to your right before entering it. Up on the ledge you will be able to find the Kuria."] },
    { "THE TWIN QUEENS WERE WROUGHT": ["image147.jpg", "image148.jpg", "image149.jpg"], "tileset": corpPost, "desc": ["", "", "You sometimes spawn inside this room, it has a platform with one door above and one door below it. The Kuria can be found ontop of the door to your right when you're walking downstairs from the platform."] }
]];